import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Header from '@/components/Header';
import About from '@/components/About';
import Services from '@/components/Services';
import Download from '@/components/Download';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AVIUTA</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={`${styles.Banner}`}>
        <Navbar />
        <Header />
      </div>
      <About />
      <Services />
      <Download />
      <Footer />
    </>
  );
}
